version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecommerce-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8443:8443"
    env_file:
      - .env
    volumes:
      - ./src/main/resources/keys/private.pem:/app/config/private.pem:ro
      - ./src/main/resources/keys/public.pem:/app/config/public.pem:ro
    environment:
      PRIVATE_KEY_PATH: /app/config/private.pem
      PUBLIC_KEY_PATH: /app/config/public.pem
    networks:
      - ecommerce-net

volumes:
  pgdata:

networks:
  ecommerce-net: