services:
  db:
    image: postgres:15-alpine
    container_name: somostiendamas-db
    environment:
      POSTGRES_DB: somostiendamas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nahuel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: somostiendamas:0.1.6.4
    container_name: somostiendamas-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # ✅ Perfil Docker con SSL
      SPRING_PROFILES_ACTIVE: docker
      
    ports:
      - "8443:8443"  # ✅ Cambio: Puerto HTTPS
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge